train_dataset:
  dataset:
    name: paired-image-folders
    args: 
      root_path_1: ./load/climate/climate_train_daily30
      root_path_2: ./load/climate/climate_train_daily60
      obs_path_3: ./data/preprocessed_daily_precip_data.csv
      meta_path: ./load/climate/meta/daily_train_60.json
      # repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-paired
    args:
      finetune: True
      sample_q: 1024
      augment: False
  batch_size: 16

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/climate/climate_val_daily30
      root_path_2: ./load/climate/climate_val_daily60
      obs_path_3: ./data/preproccessed_obs_2010_2019.csv
      meta_path: ./load/climate/meta/daily_val_60.json
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-paired
    args: 
      sample_q: 1024
      augment: False
      finetune: True
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif
  args:
    encoder_spec:
      name: rdn
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list:
        - 256
        - 256
        - 256
        - 256

optimizer:
  name: adam
  args: 
    lr: 1.e-4
resume: ./save/_climate_2x_rdn/epoch-900.pth
epoch_max: 1200
multi_step_lr: 
  milestones: [200, 400, 600, 800, 1100]
  gamma: 0.5

epoch_val: 1
epoch_save: 100
